export const
    ADD_NAME = 'ADD_NAME',
    SOME_CONST = 'SOME_CONST',
    ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED',
    ITEMS_IS_LOADING = 'ITEMS_IS_LOADING',
    ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS',
    DISPATCH_VISIBLE_HEROES = 'DISPATCH_VISIBLE_HEROES';